10 CLS
20 PRINT "polar attack"
30 PRINT "PRESS THE REQUESTED 3 KEYS      (A TO Z) TO READY! AIM! FIRE!"
40 PRINT "llama race"
50 PRINT "PICK A LLAMA AND HOPE IT WINS!"
60 PRINT "robot arm grab"
70 PRINT "PRESS A TO EXTEND THE ROBOTS ARMGRAB THE GOLD + AVOID BLUE ACID"
80 PRINT "speed trek"
90 PRINT "ROCK, PAPERS, SCISSORS IN SPACE"
120 PRINT "yeti hunt"
130 PRINT "FIND THE YETI IN THE FOREST."
140 PRINT @480,"    PRESS ANY KEY TO GO BACK"; 
200 A$=INKEY$:IFA$=""THEN200
400 CLS:PRINT@12,"LOADING":RUN"M.BAS"